# Generated by Django 3.0 on 2020-01-03 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20200103_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='create_date',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='homework_score',
            old_name='create_date',
            new_name='create_time',
        ),
    ]
