# Generated by Django 3.0 on 2020-01-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_auto_20200103_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework_score',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
