# Generated by Django 3.0 on 2020-01-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_homework_score_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework_score',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
