# Generated by Django 3.0 on 2020-01-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('realname', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=20)),
                ('grade', models.IntegerField()),
                ('userIcon', models.CharField(max_length=30)),
            ],
        ),
    ]
